export default {
    clients : [
        {
            id : 0,
            column: 'name',
            columname : 'Nombre',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column: 'primarycolor',
            columname : 'Color primario',
            type : 'color',
            class : 'col text-center',
        },
        {
            id : 2,
            column: 'backgroundcolor',
            columname : 'Color de fondo',
            type : 'color',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'accion',            
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center'
        }
    ],
    path : [
        {
            id : 0,
            column: 'name',
            columname : 'Nombre de Ruta',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column: 'customer',
            columname : 'Clientes',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column: 'kilometers',
            columname : 'Kilometraje',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column: 'url_route_input',
            columname : 'Ruta de entrada',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column: 'url_route_output',
            columname : 'Ruta de salida',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'Accións',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        },        
    ],
    driver : [
        {
            id : 0,
            column : 'clave',
            columname : 'Clave',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'name',
            columname : 'Nombre',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column : 'lastname',
            columname : 'Apellido',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'unitymovile',
            columname : 'Unidad Móvil',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column : 'address',
            columname : 'Dirección',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column : 'phone',
            columname : 'Teléfono',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 6,
            column : 'cellphone',
            columname : 'Celular',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 7,
            column : 'cellphoneNetwork',
            columname : 'Celular Red',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 8,
            column : 'photo',
            columname : 'Foto',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 9,
            column : 'accion',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        }
    ],
    truck : [
        {
            id : 0,
            column : 'numUnidad',
            columname : 'Unidad',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'driver',
            columname : 'Operador',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column : 'type',
            columname : 'Tipo',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'model',
            columname : 'Modelo',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column : 'marca',
            columname : 'Marca',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column : 'subMarca',
            columname : 'Sub Marca',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 6,
            column : 'combustible',
            columname : 'Combustible',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 7,
            column : 'performance',
            columname : 'Rendimiento',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 8,
            column : 'performance',
            columname : 'Rend. real',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 9,
            column : 'poliza',
            columname : 'Pó liza de seguro',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 10,
            column : 'gps',
            columname : 'GPS',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 11,
            column : 'photo',
            columname : 'Foto',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 12,
            column : 'taller',
            columname : 'Taller',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 13,
            column : 'tirada',
            columname : 'Tirada',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 14,
            column : 'accion',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        },
    ],
    supervisor : [
        {
            id : 0,
            column : 'name',
            columname : 'Nombre',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'customer',
            columname : 'Cliente',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column : 'phone',
            columname : 'Teléfono',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'userType',
            columname : 'Tipo',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column : 'accion',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        },                                
        
    ],
    station : [
        {
            id : 0,
            column : 'idStation',
            columname : 'ID estación',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'name',
            columname : 'Nombre',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column : 'address',
            columname : 'Dirección',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'location',
            columname : 'Ubicación',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column : 'accion',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        },
    ],
    banner : [
        {
            id : 0,
            column : 'name',
            columname : 'Titulo',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'description',
            columname : 'Descripción',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'img',
            columname : 'Imagen',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column : 'accion',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        }               
    ],
    region : [
        {
            id : 0,
            column : 'name',
            columname : 'Nombre',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'accion',
            columname : 'Acción',
            type : 'accion',
            class : 'col text-center',
        }
    ],
    programming : [
        {
            id : 0,
            column: 'code',
            columname : 'Código',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column: 'path',
            columname : 'Ruta',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column: 'pax',
            columname : 'PAX',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column: 'llegada',
            columname : 'Llegada',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column: 'turn',
            columname : 'Turno',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'timeinit',
            columname : 'Hora inicio',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 6,
            column: 'timeend',
            columname : 'Hora fin',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 7,
            column: 'driver',
            columname : 'Operador',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'commnets',
            columname : 'Comentarios',
            type : 'text',
            class : 'col text-center',
        },  
    ],
    comments : [
        {
            id : 0,
            column: 'date',
            columname : 'Fecha',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column: 'truck',
            columname : 'Unidad',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column: 'driver',
            columname : 'Operador',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column: 'path',
            columname : 'Ruta',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column: 'turn',
            columname : 'Turno',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'comments',
            columname : '',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 6,
            column: 'category',
            columname : 'Categorias',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 7,
            column: 'Subcategory',
            columname : 'Sub',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'modul',
            columname : 'Modulo',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'review',
            columname : 'Revisado',
            type : 'text',
            class : 'col text-center',
        }, 
    ],
    gasoline : [ 
        {
            id : 0,
            column : 'unidad',
            columname : 'UNIDAD',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column : 'ltr',
            columname : 'LITROS',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column : 'cost',
            columname : 'COSTO',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 3,
            column : 'cu',
            columname : 'C.U',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column : 'km_rend_real',
            columname : 'KM REND. REAL',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column : 'km_recorridos',
            columname : 'KM RECORRIDOS',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 6,
            column : 'date_upload',
            columname : 'FECHA CARGA',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 7,
            column : 'time_ipload',
            columname : 'TIEMPO CARGA',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 8,
            column : 'driver',
            columname : 'OPERADOR',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 9,
            column : 'station',
            columname : 'ESTACIÓN',
            type : 'text',
            class : 'col text-center',
        },
    ],
    programminReport : [
        {
            id : 0,
            column: 'date',
            columname : 'Fecha',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column: 'client',
            columname : 'Cliente',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column: 'truck',
            columname : 'Unidad',
            type : 'text',
            class : 'col text-center',
        },        
        {
            id : 3,
            column: 'driver',
            columname : 'Operador',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 4,
            column: 'path',
            columname : 'Ruta',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 5,
            column: 'turn',
            columname : 'Turno',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 6,
            column: 'sentido',
            columname : 'Sentido',
            type : 'text',
            class : 'col text-center',
        },
    ],
    driverWithoutpath : [
        {
            id : 0,
            column: 'name',
            columname : 'Nombre',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 1,
            column: 'lastbame',
            columname : 'Apellios',
            type : 'text',
            class : 'col text-center',
        },
        {
            id : 2,
            column: 'clave',
            columname : 'Clave',
            type : 'text',
            class : 'col text-center',
        },
    ],
    routerDataHeader : [
        {
            id : 0,
            name : 'Nombre Ruta', 
        },
        {
            id : 1,
            name : 'Cliente'
        },
        {
            id : 2,
            name : 'Kilometraje',
        },
        {
            id : 3,
            name : 'Ruta Entrada',
        },
        {
            id : 4,
            name : 'Ruta Salida',
        },
        {
            id : 5,
            name : 'Acción'
        }
    ],

}