export const driverModel = () => ({
    name: '',
    lastname: '',
    clave: '',
    rfc: '',
    address: '',
    cellphone: '',
    phone: '',
    cellphoneNetwork: '',
    seguroSocial: '',
    noLicenciaEstatal: '',
    vigLicenciaEstatal: '',
    noLicenciaFederal: '',
    vigLicenciaFederal : '',
    passwordXR : '',
    typeBlood : '',
    region : '',
    active : false,
});
